### ISSUE TITLE
Error when running npm run dev from fresh install

### ISSUE THREAD

**Issue by pat270** [natecavanaugh/github-pulls#4]
`[0] ERROR in ./app/app/components/Icon.js`
`[0] Module not found: Error: Cannot resolve 'file' or 'directory ../../bower_components/lexicon/release/images/icons in /github-pulls/app/app/components`
`[0]  @ ./app/app/components/Icon.js 22:11-102`
`[0]`
`[0] ERROR in ./~/css-loader!./~/sass-loader!./app/app/scss/main.scss`
`[0] Module build failed:`
`[0] @import "lexicon/release/scss/atlas";`
`[0] ^`
`[0]       File to import not found or unreadable: lexicon/release/scss/atlas`
`[0] Parent style sheet: /github-pulls/app/app/scss/_base.scss`
`[0]       in /github-pulls/app/app/scss/_base.scss (line 6, column 1)`
`[0]  @ ./app/app/scss/main.scss 4:14-127 13:2-17:4 14:20-133`

Had to install bower
then I ran bower install in /github-pulls/app
then got

`[0] ERROR in ./~/css-loader!./~/sass-loader!./app/app/scss/main.scss`
`[0] Module build failed: CssSyntaxError: /css-loader!/github-pulls/node_modules/sass-loader/index.js!/github-pulls/app/app/scss/main.scss:6839:25: Missed semicolon`
`[0]     at Input.error (/github-pulls/node_modules/postcss/lib/input.js:61:22)`
`[0]     at Parser.checkMissedSemicolon (/github-pulls/node_modules/postcss/lib/parser.js:495:26)`
`[0]     at Parser.decl (/github-pulls/node_modules/postcss/lib/parser.js:270:50)`
`[0]     at Parser.word (/github-pulls/node_modules/postcss/lib/parser.js:135:30)`
`[0]     at Parser.loop (/github-pulls/node_modules/postcss/lib/parser.js:60:26)`
`[0]     at parse (/github-pulls/node_modules/postcss/lib/parse.js:26:12)`
`[0]     at new LazyResult (/github-pulls/node_modules/postcss/lib/lazy-result.js:61:24)`
`[0]     at Processor.process (/github-pulls/node_modules/postcss/lib/processor.js:34:16)`
`[0]     at processCss (/github-pulls/node_modules/css-loader/lib/processCss.js:188:11)`
`[0]     at Object.module.exports (/github-pulls/node_modules/css-loader/lib/loader.js:24:2)`
`[0]  @ ./app/app/scss/main.scss 4:14-127 13:2-17:4 14:20-133`

**Comment by natecavanaugh** [comment]
Heya Patrick,
Thanks for filing this, and I'll make sure to update the docs that bower is needed (or, I'll see if I can eliminate it as a requirement for the enduser).

However, part of the issue is because of broken CSS in Lexicon here: https://github.com/liferay/lexicon/blob/master/src/scss/lexicon-base/_cards.scss#L51

I guess the CSS loader in Webpack chokes on it when trying to parse it, so it's kind of a mix between those two issues.

I'll file a ticket in Lexicon (as I found there are other issues with the release process).

Thanks Patrick :)
