### ISSUE TITLE
Comments made to commits do not contribute to the "comment count"

### ISSUE THREAD

**Issue by blzaugg** [natecavanaugh/github-pulls#6]
Not sure if this is by design or not. I'd assume all comments would be counted.

Comments made to commits do not contribute to the "comment count". Only Pull Request comments show in the "comment count".

![comments](https://cloud.githubusercontent.com/assets/1626739/16461865/80f66092-3de3-11e6-9e71-05df08c370ca.PNG)

Some thoughts. Would comments on SHAs (identical), from previous unrelated PRs, make it into a Pull Request "conversation"? If so, this ticket by be a bad idea.

**Comment by natecavanaugh** [comment]
Heya Byran,
Thanks for filing this. According to the [Github API](https://developer.github.com/v3/pulls/comments/), there are 3 types of comments, PR Comments, Issue Comments, and Commit Comments (which they consider outside of the PR view, even though it incorporates them in their view).
When you view it from this view: https://github.com/blzaugg/liferay-portal-ee/pulls
You can see that it only lists 2 comments as well.

To answer your other question, yes, that would happen if there were to be a SHA collision, since the GH API requests the comments by SHA on the repo itself.

Personally, I'm not sure if it would be useful to include the commit comments, since whenever they push up new commits, it will squash them in the web view, and say they're outdated commits.

Also, I think in the Github approach, they assume that the history will stay pretty intact, so that the commit comments will still be there on your repo when you merge a PR in.
In Liferay, since we're rebasing, we can't assume that as easily, so since commits are so transient, I'm not sure if we'd want to count these.

Let me know what you think though :)

Thanks Byran,

**Comment by blzaugg** [comment]
With the older comments on SHAs, possibly being out of scope, I'd opt to leave it as is. Thanks.
